name: Build Basilisk MacOS

on:
  workflow_dispatch:
  workflow_call:
   inputs:
    GENERATE_RELEASE_FILES:
       required: true
       type: boolean
    UPLOAD_FILES:
        required: true
        type: boolean 

jobs:
  build-basilisk:
    name: Build Basilisk MacOS -  ${{ matrix.config.name }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - name: intel64
            arch: intel64
            compiler-arch: x86_64
          - name: arm64
            arch: arm64
            compiler-arch: aarch64
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MacOS 11.3 SDK
        run: |
          mkdir -p /Applications/Xcode_16.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
          wget https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX11.3.sdk.tar.xz -P /Applications/Xcode_16.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
          tar xf /Applications/Xcode_16.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk.tar.xz -C /Applications/Xcode_16.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
          rm -rf /Applications/Xcode_16.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk.tar.xz

      - name: Install Dependencies
        run: |
          brew install yasm pyenv
          
          # Setup Python 2 with pyenv
          pyenv install 2.7.18
          pyenv global 2.7.18

      - name: Copy mozconfig
        run: cp mozconfigs/macos/${{ matrix.config.arch }}/macos-${{ matrix.config.arch }}-mozconfig .mozconfig

      - name: Build Basilisk
        run: |
          # Use Python 2 we installed earler
          export PATH="$(pyenv root)/shims:${PATH}"
          
          ./mach configure
          ./mach build
          ./mach package
          
      - uses: actions/upload-artifact@v4
        if: ${{ inputs.UPLOAD_FILES == true}}
        with:
          name: basilisk-macos-${{ matrix.config.arch }}
          path: |
            obj-${{ matrix.config.compiler-arch }}-apple-darwin/dist/*.app
            obj-${{ matrix.config.compiler-arch }}-apple-darwin/dist/basilisk-*
