name: Build Basilisk Linux i686

on:
  workflow_dispatch:
  workflow_call:
   inputs:
    GENERATE_RELEASE_FILES:
     required: true
     type: boolean
    UPLOAD_FILES:
     required: true
     type: boolean

jobs:
  build-basilisk:
    name: Build Basilisk Linux ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
          - name: GTK3 i686
            gtk: gtk3
            arch: i686
          - name: GTK2 i686
            gtk: gtk2
            arch: i686
    steps:
      - name: Free Disk Space
        run: |
          sudo apt-get update
          sudo apt-get remove -y *dotnet* *google-cloud* *aws* *php* google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy mozconfig
        run: cp mozconfigs/linux/${{ matrix.config.arch }}/${{ matrix.config.gtk }}_unofficial_branding.mozconfig .mozconfig

      - name: Update mozconfig if generating release files is true
        if: ${{ inputs.GENERATE_RELEASE_FILES == true}}
        run: |
          sed -i 's/disable-updater/enable-updater/g' .mozconfig

      - name: Update docker build script if generating release files is true
        if: ${{ inputs.GENERATE_RELEASE_FILES == true}}
        run: |
          echo 'su -c "./mach mar" $USERNAME' >> build-scripts/linux/build_basilisk_subscripts/run_inside_docker.sh

      # Restore ccache cache
      - name: Restore CCache Cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ matrix.config.gtk }}-${{ matrix.config.arch }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ccache-${{ github.ref }}-${{ matrix.config.gtk }}-${{ matrix.config.arch }}

      - name: Build Basilisk
        run: ./build-scripts/linux/build_basilisk.sh

      - uses: actions/upload-artifact@v4
        if: ${{ inputs.UPLOAD_FILES == true}}
        with:
          name: basilisk-linux-${{ matrix.config.arch }}-${{ matrix.config.gtk }}
          path: obj-${{ matrix.config.arch }}-unknown-linux-gnu/dist/basilisk-*

      # Save ccache cache
      - name: Save CCache Cache
        if: always() # Ensures the cache step runs even if the build fails
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ matrix.config.gtk }}-${{ matrix.config.arch }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-ccache-${{ github.ref }}-${{ matrix.config.gtk }}-${{ matrix.config.arch }}
        continue-on-error: true
